#!/usr/bin/env node
/* Bundles lessons/*.md into js/course-data.js so the site works when opened
   straight from disk (file://), with no web server needed.

   Usage:
     node build.js           build once
     node build.js --watch   rebuild whenever a lesson changes */
'use strict';

const fs = require('fs');
const path = require('path');

const LESSONS_DIR = path.join(__dirname, 'lessons');
const OUT_FILE = path.join(__dirname, 'js', 'course-data.js');

function parseFrontmatter(src, file) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) throw new Error(file + ': missing --- frontmatter --- block');
  const meta = {};
  m[1].split(/\r?\n/).forEach(line => {
    const i = line.indexOf(':');
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim().replace(/^"(.*)"$/, '$1');
  });
  return { meta, body: src.slice(m[0].length) };
}

function build() {
  const course = JSON.parse(fs.readFileSync(path.join(LESSONS_DIR, 'course.json'), 'utf8'));
  const partIds = new Set(course.parts.map(p => p.id));
  const files = fs.readdirSync(LESSONS_DIR).filter(f => /^\d+.*\.md$/.test(f)).sort();
  const seen = new Set();

  const lessons = files.map(file => {
    const { meta, body } = parseFrontmatter(fs.readFileSync(path.join(LESSONS_DIR, file), 'utf8'), file);
    ['id', 'title', 'part'].forEach(k => { if (!meta[k]) throw new Error(file + ': frontmatter needs "' + k + '"'); });
    if (seen.has(meta.id)) throw new Error(file + ': duplicate lesson id "' + meta.id + '"');
    if (!partIds.has(Number(meta.part))) throw new Error(file + ': unknown part ' + meta.part);
    seen.add(meta.id);
    return {
      id: meta.id,
      title: meta.title,
      part: Number(meta.part),
      minutes: Number(meta.minutes) || 15,
      summary: meta.summary || '',
      body: body.trim() + '\n'
    };
  });

  const data = { parts: course.parts, lessons };
  const out = '/* Generated by build.js from lessons/*.md. Do not edit by hand. */\n' +
    'window.COURSE = ' + JSON.stringify(data) + ';\n';
  fs.writeFileSync(OUT_FILE, out);
  console.log('Built ' + lessons.length + ' lessons in ' + course.parts.length + ' parts → js/course-data.js');
}

build();

if (process.argv.includes('--watch')) {
  let timer = null;
  console.log('Watching lessons/ for changes…');
  fs.watch(LESSONS_DIR, () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try { build(); } catch (e) { console.error(e.message); }
    }, 100);
  });
}
